apiVersion: v1
kind: Pod
metadata:
  name: book-pod # pod name
  labels:
    project: book-api # this label will be used later by the service to load balance
spec:
  containers:
    - name: book-api-ctnr # container name
      image: greengorilla7/book-api
      ports:
        - containerPort: 8080 # exposed port
